### PR TITLE
Stylelint v14 support

### PR DESCRIPTION
**Pull request by doochik**

### CODE REVIEW

**Comment by alSergey** [comment]
@jonathantneal @ybiquitous @romainmenke are you going to update the plugin? I use it and get peerDependencies conflicts on `stylelint@14`.

**Comment by romainmenke** [comment]
I don't have publishing rights for any plugin/package under the csstools org :)

**Comment by alSergey** [comment]
Do you know who has the rights and can update the plugin?

**Comment by romainmenke** [comment]
I've pinged @jonathantneal via another channel :)

**Comment by alSergey** [comment]
@romainmenke @jonathantneal hi, any update news? I'm really looking forward to the update

**Comment by romainmenke** [comment]
@alSergey No news.
You can always fork and publish an update on your own.
That will help you get unblocked :)

**Comment by jonathantneal** [comment]
This was also released in 2.0.1.

**Comment by romainmenke** [comment]
Thank you @jonathantneal 🎉

**Comment by alSergey** [comment]
Thank you 🎉

**Pull request merged**
